#!/usr/bin/python

import sys
from getopt import getopt

ignores = {
"node": """
node_modules 
logs 
npm-debug.log*"
.grunt"
coverage"
""",

"vim": """
*~
*.swp"
""",

"c": """
*.o
*.ko
*.obj
*.elf
*.gch
*.pch
*.lib
*.a
*.la
*.lo
*.dll
*.so
*.so.*
*.dylib
*.exe
*.out
*.app
*.i*486
*.x86_64
*.hex
""",

"ruby": """
*.gem
*.rbc
./config
/coverage/
/pkg/
/tmp/
/test/tmp
.dat*
build/
/doc/
.rvmrc
""",

"rust": """
*.o
*.so
*.rlib
*.dll
*.exe
/target
""",

"python": """
__pycache__/
*.py[cod]
*$py.class
*.log
Python
env/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
*.egg-info/
*.egg
.installed.cfg
"""

}

def list_lang():
    print("Available ignores listing: ")
    for lang in ignores:
        print("    " + lang)

def usage():
    print("""
usage: gignore [flags]* [language]+
flags:
    -h to get help
    -l to list all available ignores
    """)

if len(sys.argv) == 1 or sys.argv[1] == "-h":
    usage()
elif sys.argv[1] == "-l":
    list_lang()
else:
    with open(".gitignore", "a") as f:
        opts, args = getopt(sys.argv, "h")

        for arg in args[1:]:
            if arg in ignores:
                f.write("\n# " + arg + "\n")
                f.write(ignores[arg])
                f.write("\n")
            else:
                print("Can't find pattern for " + arg)
                print("Please suggest contributing to project. More info in README")

