#!/usr/bin/python

import sys
from getopt import getopt
import os

def parse(f):
    s = f.split(".")
    return s[0].lower()

ignores = {}
path = os.path.expanduser("~") + "/.handy-console/ignores"

for filename in os.listdir(path):
    with open(path + "/"  + filename, 'r') as f:
        ignores[parse(filename)] = f.read()

def list_lang():
    print("Available ignores listing: ")
    for lang in ignores:
        print("    " + lang)

def usage():
    print("""
usage: gignore [flags]* [language]+
flags:
    -h to get help
    -l to list all available ignores
    """)

if len(sys.argv) == 1 or sys.argv[1] == "-h":
    usage()
elif sys.argv[1] == "-l":
    list_lang()
else:
    with open(".gitignore", "a") as f:
        opts, args = getopt(sys.argv, "h")

        for arg in args[1:]:
            if arg in ignores:
                f.write("\n# " + arg + "\n")
                f.write(ignores[arg])
                f.write("\n")
            else:
                print("Can't find pattern for " + arg)
                print("Please suggest contributing to project. More info in README")

