#!/usr/bin/python

import sys

import handy_utils as utils

from getopt import getopt

out = "git pull".split()

if len(sys.argv) == 1:
    out.append("origin")
elif len(sys.argv) == 2:
    out.append(sys.argv[1])

out.append("master")

utils.call(out)
